language: python
python:
  - "3.6.3"
  - "3.6-dev"  # 3.6 development branch
# command to install dependencies
env:
  matrix:
  - PYMATGEN_VERSION=2017.8.4
  - PYMATGEN_VERSION=2017.9.1
  - PYMATGEN_VERSION=2017.10.16
  - PYMATGEN_VERSION=2018.1.19
  - PYMATGEN_VERSION=2018.7.15
  - PYMATGEN_VERSION=2019.1.13
  - PYMATGEN_VERSION=2019.7.30
before_install:
  - pip install --upgrade pip
  - pip install pymatgen==$PYMATGEN_VERSION
install:
  - pip install .
# command to run tests
script:
  - cd tests && cd auto_test && python -m unittest && cd ../data &&  python -m unittest && cd ../generator && python -m unittest && cd ../database && python -m unittest  && cd ../..
