blank_issues_enabled: false
contact_links:
  - name: Submit DeePMD-kit issue
    url: https://github.com/deepmodeling/deepmd-kit/issues
    about: If the issue is related to DeePMD-kit (model training and inference), submit to deepmd-kit repository
  - name: Submit dpdata issue
    url: https://github.com/deepmodeling/dpdata/issues
    about: If the issue is related to dpdata (format conversion), submit to dpdata repository
  - name: Submit dpdispatcher issue
    url: https://github.com/deepmodeling/dpdispatcher/issues
    about: If the issue is related to dpdispatcher (job submission), submit to dpdispatcher repository
  - name: Request for Help
    url: https://github.com/deepmodeling/dpgen/discussions/new?category=q-a
    about: If you have an usage question